Day 1

In [15]:
import numpy as np

In [1]:
raw =[]

with(open('depth_dataset.txt', 'r')) as f:
    for line in f:
        raw.append(int(line.strip()))



In [2]:
increased =[]
prev=0
for i,item in enumerate(raw):
    if item>prev:
        increased.append(item)
    prev = item

print(len(increased)-1)

1400


In [3]:
groups=[]
increased=[]
for i,_ in enumerate(raw):
    if i+2 >= len(raw):
        break
    groups.append(raw[i] + raw[i+1] + raw[i+2])

prev=0
for i,item in enumerate(groups):
    if item>prev:
        increased.append(item)
    prev=item

print(len(increased)-1)

1429


DAY 2

In [4]:
raw =[]


with(open('day2_dataset.txt', 'r')) as f:
    for line in f:
        raw.append(line.strip())

print(raw)

['forward 1', 'down 6', 'forward 8', 'up 3', 'down 1', 'down 4', 'down 7', 'down 3', 'down 6', 'up 8', 'down 3', 'forward 8', 'up 4', 'forward 8', 'up 5', 'down 3', 'up 2', 'forward 3', 'forward 1', 'forward 1', 'up 4', 'down 6', 'forward 5', 'down 7', 'down 1', 'down 5', 'down 6', 'up 5', 'down 2', 'forward 7', 'down 9', 'forward 5', 'up 6', 'forward 2', 'down 2', 'down 2', 'down 1', 'forward 6', 'forward 8', 'up 5', 'down 6', 'down 7', 'forward 5', 'up 7', 'down 9', 'down 9', 'down 3', 'down 3', 'forward 1', 'down 2', 'up 8', 'down 1', 'down 7', 'down 4', 'forward 6', 'up 8', 'up 8', 'up 5', 'up 4', 'down 9', 'forward 4', 'down 3', 'down 8', 'up 8', 'up 7', 'down 3', 'forward 2', 'forward 3', 'forward 4', 'forward 9', 'up 2', 'forward 9', 'up 5', 'up 9', 'down 9', 'forward 2', 'down 7', 'down 2', 'forward 7', 'down 3', 'down 9', 'down 8', 'up 3', 'up 4', 'down 8', 'down 8', 'up 7', 'up 7', 'up 2', 'up 9', 'up 6', 'forward 7', 'forward 9', 'forward 1', 'up 9', 'down 2', 'forward 9', '

In [7]:
options ={
    "forward":1,
    "up":-1,
    "down":1
}

forward = 0
depth = 0

aim=0



In [6]:
for i, item in enumerate(raw):
    subitems = item.split(' ')
    increase = options[subitems[0]] * int(subitems[1])
    if str(subitems[0]) != "forward":
        depth=depth+increase
    else:
        forward=forward+increase


print(forward*depth)

1714950


In [8]:
for i, item in enumerate(raw):
    subitems = item.split(' ')
    delta = options[subitems[0]] * int(subitems[1])

    if str(subitems[0]) != "forward":
        aim = aim + delta
        # depth= depth+delta
    else:
        forward=forward+delta
        depth = depth + aim*delta

print(forward*depth)

1281977850


DAY 3

In [9]:
raw =[]


with(open('day3_dataset.txt', 'r')) as f:
    for line in f:
        raw.append(line.strip())

print(raw)

['010011001001', '110101011110', '111111000101', '100111111001', '000000011111', '111100100111', '011111100000', '001001011100', '101100111011', '010001010100', '111011001010', '010001100011', '110110011011', '011011000001', '001100101100', '001000101100', '100000001010', '001111110000', '100101000000', '010000100000', '010100110000', '110000111101', '000001011010', '000011011001', '011000101110', '100011100101', '110010010100', '001110110101', '100011000000', '110100111100', '100100001111', '010110011001', '000001111101', '100001000010', '110010101110', '000101001100', '100100010010', '111111101000', '001010111001', '100101000001', '001101101110', '101100011010', '100100011100', '111100000111', '101011000100', '110000101010', '101100111010', '101100010101', '001011111101', '011010000110', '001101000011', '110001001110', '011010101111', '001111111011', '001100100001', '111010110001', '011011111100', '001011111001', '111110111110', '011111001011', '110110011101', '111110011011', '101101

In [10]:
processed = []
for _ in raw[0]:
    processed.append([])

for item in raw:
    for i,_ in enumerate(item):
        processed[i].append(int(item[i]))

eps=[]
gam=[]

for item in processed:
    length = len(item)
    delta = sum(item)
    if length/2<delta:
        gam.append("1")
        eps.append("0")
    else:
        gam.append("0")
        eps.append("1")


place1=""
place2=""


val1 = int(place1.join(gam),base=2)
val2 = int(place2.join(eps),base=2)



print(val1*val2)




1071734


In [11]:
raw =[]


with(open('day3_dataset.txt', 'r')) as f:
    for line in f:
        raw.append(line.strip())

print(raw)

['010011001001', '110101011110', '111111000101', '100111111001', '000000011111', '111100100111', '011111100000', '001001011100', '101100111011', '010001010100', '111011001010', '010001100011', '110110011011', '011011000001', '001100101100', '001000101100', '100000001010', '001111110000', '100101000000', '010000100000', '010100110000', '110000111101', '000001011010', '000011011001', '011000101110', '100011100101', '110010010100', '001110110101', '100011000000', '110100111100', '100100001111', '010110011001', '000001111101', '100001000010', '110010101110', '000101001100', '100100010010', '111111101000', '001010111001', '100101000001', '001101101110', '101100011010', '100100011100', '111100000111', '101011000100', '110000101010', '101100111010', '101100010101', '001011111101', '011010000110', '001101000011', '110001001110', '011010101111', '001111111011', '001100100001', '111010110001', '011011111100', '001011111001', '111110111110', '011111001011', '110110011101', '111110011011', '101101

In [14]:
processed = []
for _ in raw[0]:
    processed.append([])

for item in raw:
    for i,_ in enumerate(item):
        processed[i].append(int(item[i]))

print(processed)




[[0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,

In [15]:
bit_length=12
new=raw
keep=raw
bit=1

for i in range(0,12):


    length = len(processed[i])
    delta = sum(processed[i])
    crit=0
    if length/2<delta:
        crit=bit
    elif length/2>delta:
        crit=abs(bit-1)
    else:
        crit=bit



    new=[]
    for k,item in enumerate(keep):
        if item[i] == str(crit):
            new.append(k)



    temp1=[]
    temp2=[]
    for x in new:

        temp1.append(keep[x])

        for z in range(0,12):
            temp2.append([])
            temp2[z].append(processed[z][x])

    keep = temp1
    processed = temp2
    if len(new) == 1:
        break



print(int(keep.pop(),2))

1679


In [16]:
print(1679 *3648)

6124992


DAY4

In [56]:
boards =[]
draw=[]
draw_counter=0
new_matrix=[]
file = open("day4_dataset.txt","r")
lines =  file.readlines()
for line in lines:

    if draw_counter<1:
        draw.append(line.strip().split(','))
        draw_counter=draw_counter+1
    elif draw_counter==1:
        draw_counter=draw_counter+1
        continue
    elif line == "\n":
        boards.append(new_matrix)
        new_matrix=[]
    else:
        matrix = line.strip().split(" ")
        while("" in matrix):
            matrix.remove("")
        dict_matrix = [[0,item] for item in matrix]
        new_matrix.append(dict_matrix)
boards.append(new_matrix)
draw = draw.pop()

print(draw
      )




['72', '99', '88', '8', '59', '61', '96', '92', '2', '70', '1', '32', '18', '10', '95', '33', '20', '31', '66', '43', '26', '24', '91', '44', '11', '15', '48', '90', '27', '29', '14', '68', '3', '50', '69', '74', '54', '4', '16', '55', '64', '12', '73', '80', '58', '83', '6', '87', '30', '41', '25', '39', '93', '60', '9', '81', '63', '75', '46', '19', '78', '51', '21', '28', '94', '7', '17', '42', '53', '13', '97', '98', '34', '76', '89', '23', '86', '52', '79', '85', '67', '84', '47', '22', '37', '65', '71', '49', '82', '40', '77', '36', '62', '0', '56', '45', '57', '38', '35', '5']


In [35]:
def check(matrix):

    for i in range(0,5):
        row_counter=0
        for j in range(0,5):
            row_counter = row_counter+matrix[i][j][0]
        if row_counter>4:
            return "bingo"

    for i in range(0,5):
        col_counter=0
        for j in range(0,5):
            col_counter = col_counter+matrix[j][i][0]
        if col_counter>4:
            return "bingo"



def GetBoardScore(matrix,prev_num):
    score=0
    for i in range(0,5):
        for j in range(0,5):
            if matrix[i][j][0] == 0:
                score = score + int(matrix[i][j][1])
    return score * int(prev_num)


def Bingo():
    for c in draw:
        for k in range(0,len(boards)):
            for i in range(0,5):
                for j in range(0,5):
                    # mark
                    if boards[k][i][j][1] == c:
                        boards[k][i][j][0] = 1
                    # check
                    if check(boards[k]) == "bingo":
                        return k,c



board, prev_num = Bingo()

print(board,prev_num)
print(boards[1])
print(GetBoardScore(boards[board],prev_num))

87 31
[[[0, '77'], [1, '95'], [0, '19'], [0, '21'], [0, '76']], [[0, '93'], [1, '92'], [0, '62'], [0, '35'], [0, '3']], [[0, '4'], [0, '29'], [0, '7'], [0, '41'], [0, '45']], [[0, '80'], [0, '50'], [0, '83'], [1, '61'], [0, '64']], [[0, '39'], [1, '32'], [0, '91'], [0, '56'], [0, '48']]]
21607


In [57]:
def check(matrix):

    for i in range(0,5):
        row_counter=0
        for j in range(0,5):
            row_counter = row_counter+matrix[i][j][0]
        if row_counter>4:
            return "bingo"

    for i in range(0,5):
        col_counter=0
        for j in range(0,5):
            col_counter = col_counter+matrix[j][i][0]
        if col_counter>4:
            return "bingo"



def GetBoardScore(matrix,prev_num):
    score=0
    for i in range(0,5):
        for j in range(0,5):
            if matrix[i][j][0] == 0:
                score = score + int(matrix[i][j][1])
    return score * int(prev_num)

winning_boards=[]
prev_nums=[]
def Bingo():
    for c in draw:
        for k in range(0,len(boards)):
            if k not in winning_boards:
                board = markBoard(k,c)
                if board:
                    winning_boards.append(board)
                    prev_nums.append(c)
                    continue

def markBoard(k,rate_num):
    for i in range(0,5):
        for j in range(0,5):
            # mark
            if boards[k][i][j][1] == rate_num:
                boards[k][i][j][0] = 1
            # check
            if check(boards[k]) == "bingo":
                return k




Bingo()
print(winning_boards)

[87, 68, 61, 29, 1, 76, 97, 20, 91, 42, 50, 45, 71, 79, 85, 40, 67, 64, 77, 86, 3, 34, 52, 81, 84, 47, 17, 73, 9, 11, 4, 49, 58, 6, 21, 93, 10, 23, 88, 35, 18, 26, 44, 90, 12, 16, 25, 98, 39, 19, 36, 41, 43, 63, 82, 96, 92, 7, 24, 31, 65, 66, 83, 8, 37, 46, 53, 75, 55, 74, 99, 2, 5, 14, 38, 32, 27, 28, 33, 51, 69, 30, 94, 57, 80, 15, 78, 13, 60, 48, 89, 95, 62, 54, 59, 70, 22, 56, 72]


In [58]:
print(prev_nums)

['31', '27', '29', '68', '50', '69', '69', '54', '4', '64', '64', '12', '12', '12', '12', '73', '73', '80', '58', '58', '83', '83', '83', '83', '83', '6', '87', '87', '30', '30', '41', '41', '41', '25', '25', '25', '39', '39', '39', '60', '9', '9', '9', '9', '81', '81', '81', '81', '75', '46', '46', '46', '46', '19', '19', '78', '51', '21', '21', '28', '28', '28', '28', '94', '94', '94', '94', '94', '7', '7', '7', '17', '17', '17', '17', '42', '53', '53', '53', '53', '53', '97', '97', '98', '98', '34', '34', '23', '23', '86', '86', '86', '52', '67', '67', '47', '22', '22', '49']


In [59]:
print(GetBoardScore(boards[72],49))


19012


DAY 5

In [157]:
raw =[]

file = open("day5_dataset.txt","r")
lines =  file.readlines()

x1=[]
x2=[]
y1=[]
y2=[]

for line in lines:
    nums = line.split(' ')
    x1.append(int(nums[0].split(',')[0]))
    y1.append(int(nums[0].split(',')[1]))
    x2.append(int(nums[2].split(',')[0]))
    y2.append(int(nums[2].split(',')[1]))

print(x1)


[62, 58, 137, 453, 178, 447, 723, 47, 387, 58, 86, 215, 496, 546, 621, 471, 175, 19, 159, 593, 167, 730, 713, 583, 39, 778, 70, 85, 689, 76, 510, 510, 780, 440, 934, 979, 379, 243, 534, 198, 871, 226, 686, 543, 506, 177, 337, 421, 858, 236, 254, 859, 89, 58, 930, 667, 512, 17, 345, 531, 67, 548, 934, 119, 769, 587, 109, 225, 544, 304, 510, 772, 867, 466, 305, 563, 566, 889, 754, 930, 70, 737, 652, 776, 484, 119, 394, 340, 715, 236, 747, 583, 609, 460, 519, 206, 507, 16, 31, 54, 844, 677, 387, 329, 970, 565, 748, 255, 146, 191, 316, 208, 885, 477, 845, 225, 858, 162, 828, 670, 732, 570, 113, 374, 850, 841, 976, 177, 969, 787, 743, 15, 863, 586, 442, 633, 21, 829, 975, 946, 531, 84, 989, 669, 128, 692, 686, 135, 837, 751, 190, 850, 229, 980, 54, 737, 533, 232, 911, 80, 880, 674, 956, 24, 516, 71, 629, 34, 983, 986, 769, 392, 577, 243, 273, 251, 989, 400, 646, 768, 93, 489, 313, 986, 322, 567, 198, 402, 897, 773, 373, 690, 884, 136, 458, 491, 558, 980, 126, 437, 53, 389, 464, 646, 919, 33

In [118]:
board =[]
square=0
for i in range(0,len(lines)):
    if square<x1[i]:
        square=x1[i]
    if square<y1[i]:
        square=y1[i]
    if square<x2[i]:
        square=x2[i]
    if square<y2[i]:
        square=y2[i]

print("square",square+1)
for i in range(0,square+1):
    board.append([])
    for j in range(0,square+1):
        board[i].append(0)

print(np.matrix(board))
data_square=len(lines)
for i in range(0,data_square):
    deltax = abs(x1[i]-x2[i])
    deltay = abs(y1[i]-y2[i])
    if x1[i] != x2[i] and y1[i] != y2[i]:
        continue
    elif deltax>0:
        small=0
        big=0
        if x1[i]>x2[i]:
            small=x2[i]
            big=x1[i]+1
        else:
            small=x1[i]
            big=x2[i]+1

        for j in range(small,big):
            board[y1[i]][j]= board[y1[i]][j]+1
    elif deltay>0:
        small=0
        big=0
        if y1[i]>y2[i]:
            small=y2[i]
            big=y1[i]+1
        else:
            small=y1[i]
            big=y2[i]+1

        for j in range(small,big):
            board[j][x1[i]]= board[j][x1[i]]+1


print(np.matrix(board))

square 991
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [120]:
count=0

for i in range(0,square+1):
    for j in range(0,square+1):
        if board[i][j] >1:
            count = count+1


print(count)

5442


In [159]:
board =[]
square=0
for i in range(0,len(lines)):
    if square<x1[i]:
        square=x1[i]
    if square<y1[i]:
        square=y1[i]
    if square<x2[i]:
        square=x2[i]
    if square<y2[i]:
        square=y2[i]

for i in range(0,square+1):
    board.append([])
    for j in range(0,square+1):
        board[i].append(0)

data_square=len(lines)
for i in range(0,data_square):
    deltax = abs(x1[i]-x2[i])
    deltay = abs(y1[i]-y2[i])
    if x1[i] != x2[i] and y1[i] != y2[i]:

        y_counter=y1[i]
        x_counter=x1[i]

        while(abs(x2[i]-x_counter)!=0 and abs(y2[i]-y_counter)!=0):

            board[y_counter][x_counter] = board[y_counter][x_counter]+1
            if x1[i]>x2[i]:
                x_counter = x_counter-1
            else:
                x_counter=x_counter+1
            if y1[i]>y2[i]:
                y_counter=y_counter-1
            else:
                y_counter=y_counter+1

        board[y_counter][x_counter] = board[y_counter][x_counter]+1
    elif deltax>0:
        small=0
        big=0
        if x1[i]>x2[i]:
            small=x2[i]
            big=x1[i]+1
        else:
            small=x1[i]
            big=x2[i]+1

        for j in range(small,big):
            board[y1[i]][j]= board[y1[i]][j]+1
    elif deltay>0:
        small=0
        big=0
        if y1[i]>y2[i]:
            small=y2[i]
            big=y1[i]+1
        else:
            small=y1[i]
            big=y2[i]+1

        for j in range(small,big):
            board[j][x1[i]]= board[j][x1[i]]+1


print(np.matrix(board))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [160]:
count=0

for i in range(0,square+1):
    for j in range(0,square+1):
        if board[i][j] >1:
            count = count+1


print(count)

19571


DAY 6

In [71]:
input=[1,4,1,1,1,1,1,1,1,4,3,1,1,3,5,1,5,3,2,1,1,2,3,1,1,5,3,1,5,1,1,2,1,2,1,1,3,1,5,1,1,1,3,1,1,1,1,1,1,4,5,3,1,1,1,1,1,1,2,1,1,1,1,4,4,4,1,1,1,1,5,1,2,4,1,1,4,1,2,1,1,1,2,1,5,1,1,1,3,4,1,1,1,3,2,1,1,1,4,1,1,1,5,1,1,4,1,1,2,1,4,1,1,1,3,1,1,1,1,1,3,1,3,1,1,2,1,4,1,1,1,1,3,1,1,1,1,1,1,2,1,3,1,1,1,1,4,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,5,1,1,1,2,2,1,1,3,5,1,1,1,1,3,1,3,3,1,1,1,1,3,5,2,1,1,1,1,5,1,1,1,1,1,1,1,2,1,2,1,1,1,2,1,1,1,1,1,2,1,1,1,1,1,5,1,4,3,3,1,3,4,1,1,1,1,1,1,1,1,1,1,4,3,5,1,1,1,1,1,1,1,1,1,1,1,1,1,5,2,1,4,1,1,1,1,1,1,1,1,1,1,1,1,1,5,1,1,1,1,1,1,1,1,2,1,4,4,1,1,1,1,1,1,1,5,1,1,2,5,1,1,4,1,3,1,1]

print(input)

[1, 4, 1, 1, 1, 1, 1, 1, 1, 4, 3, 1, 1, 3, 5, 1, 5, 3, 2, 1, 1, 2, 3, 1, 1, 5, 3, 1, 5, 1, 1, 2, 1, 2, 1, 1, 3, 1, 5, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 4, 5, 3, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 4, 4, 4, 1, 1, 1, 1, 5, 1, 2, 4, 1, 1, 4, 1, 2, 1, 1, 1, 2, 1, 5, 1, 1, 1, 3, 4, 1, 1, 1, 3, 2, 1, 1, 1, 4, 1, 1, 1, 5, 1, 1, 4, 1, 1, 2, 1, 4, 1, 1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 2, 1, 4, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 5, 1, 1, 1, 2, 2, 1, 1, 3, 5, 1, 1, 1, 1, 3, 1, 3, 3, 1, 1, 1, 1, 3, 5, 2, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 5, 1, 4, 3, 3, 1, 3, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 3, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 2, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 2, 5, 1, 1, 4, 1, 3, 1, 1]


In [72]:


new_day = dict()

for item in input:
    new_day[item] = new_day.get(item,0) +1
for_viz=[]
jellies=0
for day in range(0,256):

    # print(new_day)
    jellies=0
    for key in range(0,9):
        if key == 0:
            jellies = new_day.get(key,0)
        else:
            new_day[key-1] = new_day.get(key,0)
    new_day[8]=jellies
    new_day[6]=new_day.get(6,0)+jellies

counter=0
for item in new_day.keys():
    counter += new_day.get(item)

# print(new_day)
print(counter)

1757714216975


DAY 7

In [34]:
input=[1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,161,185,311,752,668,728,210,741,636,381,1222,509,282,156,806,624,31,300,711,128,146,368,306,239,7,519,441,368,179,155,704,274,237,710,164,55,217,1007,0,701,812,713,127,536,320,163,454,310,726,433,426,102,1350,736,408,951,307,15,333,462,755,797,265,540,680,357,914,195,468,1034,583,413,1293,450,88,2,208,1006,336,98,17,164,95,455,511,113,710,636,308,330,479,62,197,591,390,148,933,1060,10,564,137,422,1756,494,1205,79,13,1257,205,738,245,462,313,249,1580,929,914,512,370,152,413,6,223,197,777,885,1387,52,824,1308,422,728,298,123,922,234,33,109,747,231,916,1452,432,397,222,857,113,119,437,1474,129,1214,69,595,347,293,885,363,72,315,77,1131,55,1541,1244,37,724,553,65,327,341,619,800,547,104,33,272,1557,1316,141,476,510,505,188,1734,175,52,222,1392,732,303,959,75,432,224,293,112,99,923,396,1069,241,246,1146,823,961,593,367,394,324,390,20,63,403,602,571,125,649,60,327,190,1661,140,486,420,833,1464,218,80,74,345,366,191,119,109,399,1596,431,445,1179,1195,144,136,51,215,19,106,998,664,89,49,1041,101,814,995,279,810,702,738,471,315,217,60,24,272,490,7,1294,322,594,804,165,130,125,18,1422,208,0,148,544,901,1530,50,207,364,904,197,585,153,536,1014,571,1086,782,727,125,1174,453,1773,0,106,790,634,385,39,91,599,48,98,128,562,595,901,1269,108,219,583,162,101,182,645,371,17,872,73,156,313,243,678,75,727,566,282,193,28,75,576,394,176,132,172,27,758,496,57,32,73,1791,208,1660,429,38,1518,419,1748,52,1193,353,175,198,186,105,195,75,867,380,417,341,574,628,1076,116,1441,1353,528,530,205,0,1434,827,556,493,884,172,187,441,182,227,954,1016,3,336,786,947,155,373,52,26,969,686,837,477,8,31,288,952,574,159,511,351,440,774,948,213,45,773,294,75,742,300,686,395,315,1658,264,119,28,993,392,99,759,384,317,1105,562,324,416,375,938,329,988,1334,439,1284,557,28,225,438,216,501,358,743,206,1150,378,30,850,1149,296,279,132,387,64,895,157,528,138,12,688,1045,153,42,54,1281,535,427,297,1037,253,68,424,428,205,138,93,82,383,93,1061,1116,287,888,204,777,35,548,784,268,897,1167,201,532,151,198,388,3,306,1689,555,207,852,723,173,655,535,963,46,54,1705,490,244,67,299,543,333,185,196,361,147,891,370,797,195,386,371,1111,156,1587,641,1252,430,40,715,930,1560,774,227,122,179,45,72,744,27,6,1479,1178,969,108,395,37,31,426,1131,495,246,36,63,121,286,594,856,2,1773,1724,5,421,51,344,1312,382,24,15,246,921,562,20,818,493,44,239,1047,368,37,245,245,851,35,2,442,792,235,516,450,282,812,510,161,731,788,93,475,205,222,1005,1002,358,860,875,1330,354,724,114,207,956,597,234,206,55,637,7,48,751,123,241,858,255,508,200,1064,79,169,85,768,255,21,708,340,145,385,1130,281,39,1072,100,285,1355,360,283,560,153,488,689,319,929,309,1013,95,88,843,208,126,146,3,328,75,251,18,1053,782,556,94,743,299,66,311,18,789,1323,45,777,281,75,676,741,340,1055,870,1935,203,80,93,1372,747,6,79,560,33,67,1,197,193,1245,40,466,1144,557,16,664,144,984,590,1105,165,131,41,455,77,33,572,477,854,18,157,48,453,487,25,423,181,800,615,25,374,183,380,262,219,81,466,691,119,754,122,918,920,410,1102,156,1355,101,395,1837,89,40,341,264,393,547,564,480,13,24,259,1054,19,390,1199,664,205,645,274,43,115,354,329,473,812,1302,771,308,94,838,593,942,1107,153,394,596,194,119,719,1392,1094,26,252,1276,162,310,23,1681,106,160,1206,509,684,432,1659,129,172,99,630,417,151,69,211,874,310,1109,740,589,496,508,742,407,1156,1920,209,218,375,468,971,705,68,1603,158,236,121,63,1615,822,198,322,946,368,128,231,125,125,41,278,574,359,28,20,322,785,382,990,266,1586,324,710,159,727,28,11,15,211,620,762,73,1,75,33,239,327,1105,228,4,1256,1578,729,1164,44,222,1177,186,1593,605,43,239,1353,877,300,75,54,324,1487,1655,715,597,540,202,266,1030,576,251,14,669,833,66,1285,170,109,433,1760,60,948,542,129,5,165,173,659,743]


In [35]:
max = np.max(input)

my_list=dict()

for item in input:
    my_list[item] = my_list.get(item,0) +1

costs=dict()
for item in range(0,max):
    cost=0
    for key in my_list.keys():
        moves = abs(item-key)
        cost +=moves*my_list.get(key,0)
    costs[item]=cost


def GetLeastCost():
    least_cost=0
    for index,key in enumerate(costs.keys()):
        if index<1:
            least_cost=costs.get(key)
        elif least_cost>costs.get(key):
            least_cost=costs.get(key)

    return least_cost
print(GetLeastCost())

328262


In [36]:
max = np.max(input)

my_list=dict()

for item in input:
    my_list[item] = my_list.get(item,0) +1

costs=dict()
for item in range(0,max):
    cost=0
    for key in my_list.keys():
        moves = abs(item-key)
        incured = sum([move for move in range(1,moves+1)])
        cost +=incured*my_list.get(key,0)
    costs[item]=cost


def GetLeastCost():
    least_cost=0
    for index,key in enumerate(costs.keys()):
        if index<1:
            least_cost=costs.get(key)
        elif least_cost>costs.get(key):
            least_cost=costs.get(key)

    return least_cost
print(GetLeastCost())

90040997
